apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-cluster1
  name: nginx-cluster1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-cluster1
  template:
    metadata:
      labels:
        run: nginx-cluster1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80